const data ={
    "days": [
        {
            "date": "12/11/2024",
            "totalStake": null,
            "netCash": null,
            "startBalance": null,
            "endBalance": null,
            "dayUrl": null,
            "games": {
                "game": [
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:13:46 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "-5000.00",
                        "balance": "-5006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629084907&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629084907              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:13:22 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "0.00",
                        "balance": "-6.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629080507&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629080507              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:12:58 GMT",
                        "dataTimeEnd": null,
                        "stake": "2500.00",
                        "netAmount": "-2500.00",
                        "balance": "-2506.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629075607&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629075607              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:12:35 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "5000.00",
                        "balance": "4993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629071907&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629071907              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:11:02 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "5000.00",
                        "balance": "4993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629054207&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629054207              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:10:38 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "5000.00",
                        "balance": "4993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629049607&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629049607              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:10:17 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "-5000.00",
                        "balance": "-5006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629045507&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629045507              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:09:55 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "-5000.00",
                        "balance": "-5006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629041407&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629041407              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:09:32 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "5000.00",
                        "balance": "4993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629037007&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629037007              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:08:45 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "-2000.00",
                        "balance": "-2006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629028307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629028307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 08:08:23 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "1000.00",
                        "balance": "993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6629024207&format=xml",
                        "totalPayoff": null,
                        "gameId": "6629024207              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 07:02:19 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "1000.00",
                        "balance": "993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628313107&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628313107              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 07:00:48 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "0.00",
                        "balance": "-6.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628296707&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628296707              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 07:00:25 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "1000.00",
                        "balance": "993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628292307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628292307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 07:00:03 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "-1000.00",
                        "balance": "-1006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628288107&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628288107              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 06:59:41 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "-1000.00",
                        "balance": "-1006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628284307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628284307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 06:59:17 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "-1000.00",
                        "balance": "-1006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628280007&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628280007              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 06:58:32 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "-1000.00",
                        "balance": "-1006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628272007&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628272007              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_1",
                        "dataTimeStart": "2024/12/11 06:57:25 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "-1000.00",
                        "balance": "-1006.67",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6628261407&format=xml",
                        "totalPayoff": null,
                        "gameId": "6628261407              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/11 06:29:05 GMT",
                        "dataTimeEnd": null,
                        "stake": "1000.00",
                        "netAmount": "1000.00",
                        "balance": "993.33",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/11/2024&currentDay=false&user_id=ppc1735063990579&game_id=6627956907&format=xml",
                        "totalPayoff": null,
                        "gameId": "6627956907              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "freeBet": false,
                        "megaBaccaratGameEvents": null
                    }
                ],
                "account": null,
                "gameDate": "12/11/2024"
            }
        }
    ]
}

const  ids = data.days[0].games.game.map((x)=>{
    return Number(x.gameId.trim()) 
})
console.log(ids)