const data= {
    "days": [
        {
            "date": "12/09/2024",
            "totalStake": null,
            "netCash": null,
            "startBalance": null,
            "endBalance": null,
            "dayUrl": null,
            "games": {
                "game": [
                    {
                        "label": "KOREAN_SPEED_BACCARAT_4",
                        "dataTimeStart": "2024/12/09 09:58:21 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "-5000.00",
                        "balance": "-5012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6599211707&format=xml",
                        "totalPayoff": null,
                        "gameId": "6599211707              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_4",
                        "dataTimeStart": "2024/12/09 09:57:01 GMT",
                        "dataTimeEnd": null,
                        "stake": "5000.00",
                        "netAmount": "-3000.00",
                        "balance": "-3012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6599198307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6599198307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_4",
                        "dataTimeStart": "2024/12/09 09:56:13 GMT",
                        "dataTimeEnd": null,
                        "stake": "4000.00",
                        "netAmount": "15000.00",
                        "balance": "14987.83",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6599190307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6599190307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:46:56 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "-2000.00",
                        "balance": "-2012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597810307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597810307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:42:00 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "0.00",
                        "balance": "-12.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597758807&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597758807              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:41:16 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "-2000.00",
                        "balance": "-2012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597751207&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597751207              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:38:32 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "0.00",
                        "balance": "-12.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597721407&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597721407              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:37:01 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "0.00",
                        "balance": "-12.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597704307&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597704307              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:36:14 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "0.00",
                        "balance": "-12.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597695507&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597695507              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:35:51 GMT",
                        "dataTimeEnd": null,
                        "stake": "2000.00",
                        "netAmount": "0.00",
                        "balance": "-12.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597691007&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597691007              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:35:30 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "12000.00",
                        "balance": "11987.83",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597687107&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597687107              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:34:46 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-6000.00",
                        "balance": "-6012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597679007&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597679007              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:34:23 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-4000.00",
                        "balance": "-4012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597674907&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597674907              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:33:36 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-4000.00",
                        "balance": "-4012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597667007&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597667007              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:33:12 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-4000.00",
                        "balance": "-4012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597662807&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597662807              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:32:27 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-4000.00",
                        "balance": "-4012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597654707&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597654707              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:32:03 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "14000.00",
                        "balance": "13987.83",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597650207&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597650207              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:31:42 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-6000.00",
                        "balance": "-6012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597645907&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597645907              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:31:18 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-4000.00",
                        "balance": "-4012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597641207&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597641207              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    },
                    {
                        "label": "KOREAN_SPEED_BACCARAT_2",
                        "dataTimeStart": "2024/12/09 07:30:54 GMT",
                        "dataTimeEnd": null,
                        "stake": "6000.00",
                        "netAmount": "-4000.00",
                        "balance": "-4012.17",
                        "gameUrl": "/cgibin/usermanagement/audit/game.jsp?lang=en&date=12/09/2024&currentDay=false&user_id=ppc1735063440017&game_id=6597636907&format=xml",
                        "totalPayoff": null,
                        "gameId": "6597636907              ",
                        "roundId": null,
                        "type": "Baccarat",
                        "currency": null,
                        "seat": null,
                        "bet": null,
                        "gameCancelled": null,
                        "multiplier": null,
                        "simulationElement": null,
                        "maxcap": false,
                        "maxcapValue": null,
                        "tableVariant": null,
                        "tableType": null,
                        "simulationStatus": "2",
                        "rngSlots": null,
                        "sweetBonanzaInfo": null,
                        "bobDetails": null,
                        "rouletteDetails": null,
                        "bingoGameEvents": null,
                        "snlGameDetails": null,
                        "kpbGameDetails": null,
                        "tiGameSummary": null,
                        "cardValues": null,
                        "snlv2GameDetails": null,
                        "megaBaccaratGameEvents": null,
                        "freeBet": false
                    }
                ],
                "account": null,
                "gameDate": "12/09/2024"
            }
        }
    ]
}